"use client";

import { useRef, useState } from "react";

interface Props {
  id: string;
  value: string;
  onChange: (v: string) => void;
  rows?: number;
}

function applyMarkdown(
  textarea: HTMLTextAreaElement,
  onChange: (v: string) => void,
  wrap: { before: string; after?: string; placeholder: string }
) {
  const { before, after = before, placeholder } = wrap;
  const { selectionStart, selectionEnd, value } = textarea;
  const selected = value.slice(selectionStart, selectionEnd) || placeholder;
  const next = value.slice(0, selectionStart) + before + selected + after + value.slice(selectionEnd);
  onChange(next);

  requestAnimationFrame(() => {
    textarea.focus();
    textarea.setSelectionRange(selectionStart + before.length, selectionStart + before.length + selected.length);
  });
}

function applyLinePrefix(textarea: HTMLTextAreaElement, onChange: (v: string) => void, prefix: string) {
  const { selectionStart, selectionEnd, value } = textarea;
  const lineStart = value.lastIndexOf("\n", selectionStart - 1) + 1;
  const next = value.slice(0, lineStart) + prefix + value.slice(lineStart);
  onChange(next);

  requestAnimationFrame(() => {
    textarea.focus();
    textarea.setSelectionRange(selectionStart + prefix.length, selectionEnd + prefix.length);
  });
}

// Minimal markdown→HTML converter for the preview panel (no external deps).
// Handles the subset generated by this toolbar: headings, bold, italic,
// links, unordered + ordered lists, blockquotes, and inline code.
function markdownToHtml(md: string): string {
  let html = md
    // Headings
    .replace(/^### (.+)$/gm, "<h3>$1</h3>")
    .replace(/^## (.+)$/gm, "<h2>$1</h2>")
    .replace(/^# (.+)$/gm, "<h1>$1</h1>")
    // Blockquote
    .replace(/^> (.+)$/gm, "<blockquote>$1</blockquote>")
    // Bold + italic (order matters)
    .replace(/\*\*\*(.+?)\*\*\*/g, "<strong><em>$1</em></strong>")
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    .replace(/_(.+?)_/g, "<em>$1</em>")
    // Inline code
    .replace(/`(.+?)`/g, "<code>$1</code>")
    // Links
    .replace(/\[(.+?)\]\((.+?)\)/g, '<a href="$2" target="_blank" rel="noopener">$1</a>')
    // Unordered list items
    .replace(/^- (.+)$/gm, "<li>$1</li>")
    // Ordered list items
    .replace(/^\d+\. (.+)$/gm, "<li>$1</li>")
    // Wrap consecutive <li> in <ul>
    .replace(/(<li>.*<\/li>\n?)+/g, (m) => `<ul>${m}</ul>`)
    // Paragraphs: blank lines separate blocks
    .split(/\n{2,}/)
    .map((block) => {
      const trimmed = block.trim();
      if (!trimmed) return "";
      if (/^<(h[1-6]|ul|ol|li|blockquote)/.test(trimmed)) return trimmed;
      return `<p>${trimmed.replace(/\n/g, "<br>")}</p>`;
    })
    .join("\n");
  return html;
}

const BTN = "rounded-md px-2 py-1 text-xs text-foreground transition-colors hover:bg-surface";
const SEP = "mx-0.5 h-4 w-px bg-border";

export default function RichTextField({ id, value, onChange, rows = 8 }: Props) {
  const textareaRef = useRef<HTMLTextAreaElement>(null);
  const [tab, setTab] = useState<"write" | "preview">("write");

  function withTextarea(fn: (el: HTMLTextAreaElement) => void) {
    if (textareaRef.current) fn(textareaRef.current);
  }

  return (
    <div>
      {/* Tab bar */}
      <div className="mb-1 flex items-center gap-1 border-b border-border">
        <button
          type="button"
          onClick={() => setTab("write")}
          className={`rounded-t-md px-3 py-1.5 text-xs font-medium transition-colors ${
            tab === "write" ? "border-b-2 border-accent text-accent-text" : "text-muted hover:text-foreground"
          }`}
        >
          Bearbeiten
        </button>
        <button
          type="button"
          onClick={() => setTab("preview")}
          className={`rounded-t-md px-3 py-1.5 text-xs font-medium transition-colors ${
            tab === "preview" ? "border-b-2 border-accent text-accent-text" : "text-muted hover:text-foreground"
          }`}
        >
          Vorschau
        </button>
      </div>

      {tab === "write" && (
        <>
          {/* Toolbar */}
          <div className="mb-1.5 flex flex-wrap items-center gap-0.5 rounded-lg border border-border bg-surface-2 p-1">
            <button
              type="button"
              title="Überschrift 2"
              onClick={() => withTextarea((el) => applyLinePrefix(el, onChange, "## "))}
              className={BTN + " font-bold"}
            >
              H2
            </button>
            <button
              type="button"
              title="Überschrift 3"
              onClick={() => withTextarea((el) => applyLinePrefix(el, onChange, "### "))}
              className={BTN + " font-bold"}
            >
              H3
            </button>
            <div className={SEP} aria-hidden />
            <button
              type="button"
              title="Fett"
              onClick={() => withTextarea((el) => applyMarkdown(el, onChange, { before: "**", placeholder: "fett" }))}
              className={BTN + " font-bold"}
            >
              F
            </button>
            <button
              type="button"
              title="Kursiv"
              onClick={() => withTextarea((el) => applyMarkdown(el, onChange, { before: "_", placeholder: "kursiv" }))}
              className={BTN + " italic"}
            >
              K
            </button>
            <div className={SEP} aria-hidden />
            <button
              type="button"
              title="Link"
              onClick={() =>
                withTextarea((el) =>
                  applyMarkdown(el, onChange, { before: "[", after: "](https://)", placeholder: "Linktext" })
                )
              }
              className={BTN + " underline"}
            >
              Link
            </button>
            <div className={SEP} aria-hidden />
            <button
              type="button"
              title="Aufzählung"
              onClick={() => withTextarea((el) => applyLinePrefix(el, onChange, "- "))}
              className={BTN}
            >
              • Liste
            </button>
            <button
              type="button"
              title="Nummerierte Liste"
              onClick={() => withTextarea((el) => applyLinePrefix(el, onChange, "1. "))}
              className={BTN}
            >
              1. Liste
            </button>
            <div className={SEP} aria-hidden />
            <button
              type="button"
              title="Blockzitat"
              onClick={() => withTextarea((el) => applyLinePrefix(el, onChange, "> "))}
              className={BTN}
            >
              Zitat
            </button>
            <button
              type="button"
              title="Code"
              onClick={() => withTextarea((el) => applyMarkdown(el, onChange, { before: "`", placeholder: "code" }))}
              className={BTN + " font-mono"}
            >
              Code
            </button>
          </div>
          <textarea
            ref={textareaRef}
            id={id}
            value={value}
            onChange={(e) => onChange(e.target.value)}
            rows={rows}
            className="w-full rounded-lg border border-border bg-background px-3.5 py-2.5 font-mono text-sm text-foreground outline-none focus:border-accent"
            placeholder="Markdown-Text…"
          />
        </>
      )}

      {tab === "preview" && (
        <div
          className="prose prose-sm prose-invert min-h-[10rem] w-full rounded-lg border border-border bg-background px-3.5 py-2.5 text-sm text-foreground [&_a]:text-accent-text [&_a]:underline [&_blockquote]:border-l-2 [&_blockquote]:border-border [&_blockquote]:pl-3 [&_blockquote]:text-muted [&_code]:rounded [&_code]:bg-surface-2 [&_code]:px-1 [&_code]:py-0.5 [&_code]:font-mono [&_h2]:text-base [&_h2]:font-bold [&_h3]:text-sm [&_h3]:font-bold [&_li]:ml-4 [&_li]:list-disc [&_p]:mb-2 [&_strong]:font-bold"
          dangerouslySetInnerHTML={{ __html: value ? markdownToHtml(value) : '<span class="text-muted">Noch kein Inhalt.</span>' }}
        />
      )}
    </div>
  );
}
